### PR TITLE
Laravel 8 support

### PR DESCRIPTION
**Pull request by saddamhussain734**
- Bump up notifications and support dependencies

### CODE REVIEW

**Comment by salamwaddah** [comment]
Received. I'll have a look at it Friday tomorrow.

**Comment by saddamhussain734** [comment]
> Received. I'll have a look at it Friday tomorrow.

Alright. Thanks

**Comment by blerimcazimi** [comment]
Any updates?

**Comment by salamwaddah** [comment]
@blerimcazimi @saddamhussain734 this is merged. you can update to `1.2`

image

**Pull request merged**
